version: '3'
services:
    php:
        build: .
        volumes:
          - '.:/var/www/html'
        depends_on:
          - composer
    composer:
        image: composer
        volumes:
            - .:/app
        command: install